[package]
name = "tie_break"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
polars = { version = "0.46.0", features = ["lazy", "polars-io", "polars-ops", "parquet", "dtype-u8", "round_series", "strings", "concat_str", "is_in"] }
noodles = { version = "0.93.0", features = ["bam", "bgzf", "core", "sam"], default-features = false }
rayon = "1.10.0"
itertools = "0.14.0"
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
indexmap = { version = "2", features = ["serde"] }
crossbeam = "0.8.4"
csv = "1.3.1"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.dev]
opt-level = 1 # needed to stop a libz conflict
debug = true

[profile.release]
opt-level = 3

[lints.clippy]
needless_return = "allow"
