name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

jobs:
  build_and_test:
    name: nf-test
    runs-on: self-hosted # Uses https://github.com/GlobalPathogenAnalysisService/git_runners
    steps:
      - name: print debug data
        run: |
          whoami
          pwd
          echo java_cmd=$JAVA_CMD
          printenv
      - name: clean up # nf-test needs to sudo to remove, so will fail automatic cleanup
        run: |
          sudo rm -rf .nf-test || true
          sudo rm -rf tests || true

      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.PAT_TOKEN }}"
          fetch-depth: 0
      
      - name: echo versions
        run: |
          nextflow -v
          nf-test version
      
      - name: softlink reference data # This has already been downloaded to the runner
        run: |
          mkdir data && \
          ln -s /mnt/portal-sp3dev-knowledge/manifest ./data/manifest && \
          tree data/manifest
          ln -s /mnt/dev-knowledge/sylph ./data/sylph
      
      - name: Login to OCR
        uses: docker/login-action@v2
        with:
          registry: lhr.ocir.io
          username: ${{ secrets.OCR_USERNAME }}
          password: ${{ secrets.OCR_TOKEN }}
      
      - name: Build docker container
        run: |
          docker build -t test_container_cm . --build-arg TESTING=true
      - name: Inspect
        run: |
          docker image inspect test_container_cm

      # Run pytest in container to use conda environment
      - name: pytest in docker
        run: |
          docker run -v ${{ github.workspace }}/tests:/app/tests \
            -v ${{ github.workspace }}/test_data:/app/test_data \
            -v /mnt/dev-knowledge/manifest:/app/data/manifest \
            -v /mnt/dev-knowledge/sylph:/app/data/sylph \
            test_container_cm pytest /app/tests

      - name: Run nf-test
        run: nf-test test tests/nextflow/*.test --profile local_docker