name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

jobs:
  build_and_test:
    name: nf-test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      # cargo test is run within the build process
      - name: Build docker container
        run: |
          docker build -t test_container_cm . --build-arg TESTING=true
      - name: Inspect
        run: |
          docker image inspect test_container_cm

      # Run pytest in container to use conda environment
      - name: pytest in docker
        run: |
          docker run -v ${{ github.workspace }}/tests:/app/tests \
            -v ${{ github.workspace }}/test_data:/app/test_data \
            test_container_cm pytest /app/tests

      - name: Run nf-test
        run: nf-test test tests/nextflow/*.test --profile local_docker
